# Generated by Django 4.0.2 on 2022-02-12 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
