# Generated by Django 4.0.2 on 2022-02-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_alter_deposit_account_alter_withdraw_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Withdraw',
            new_name='Operation',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
