# Generated by Django 4.0.2 on 2022-02-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_rename_withdraw_operation_delete_deposit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget',
            new_name='Account',
        ),
    ]
