# Generated by Django 4.0.2 on 2022-02-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_operation_operation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date_created',
            field=models.DateField(blank=True),
        ),
    ]
